spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_vendor?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: waris1918

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
